### ISSUE TITLE
Project Status

### ISSUE THREAD

**Issue by fire** [GetFirefly/firefly#698]
Looking at the logs, all activity ceased on Mar 26, 2021.

**Comment by bcardarella** [comment]
@fire thanks for asking, we have been stalled. However, @bitwalker and I spoke last week and we have a plan to get the project moving forward again hopefully before EOY. Apologies!

**Comment by bitwalker** [comment]
@fire I've actually got a local branch with work on it that has been ongoing this year, but movement has been slow due to my day job demands. As @bcardarella mentioned, I'm dedicating more time to the project moving forward and aiming to get us in a better position for community contribution to avoid this happening again. We've also been delayed on the WebAssembly front as the Stack Subgroup works through various proposals for introducing stack switching primitives, although there are plenty of other areas we could focus our attention on while waiting for that, it has made it difficult to commit to specific architectural decisions in the backend of the compiler. 

This past year has mostly been reworking the backend to decouple the various target platforms from each other (namely Wasm vs _everything else_). I've also been moving more of the compiler backend into Rust, with the aim to allow contributors to be able to do more without having to switch between Rust and C++ to make changes, and to reduce the complexity of the backend. So while there hasn't been much movement publically on Lumen, I have been doing quite a bit still, its just slow going.

We're very much still invested in this project, I hope you'll bear with us :)

**Comment by fire** [comment]
I suggest working in the open. Thanks for the update.

**Comment by fire** [comment]
Heart beat check.

![image](https://user-images.githubusercontent.com/32321/148592036-0c5bc05a-fa76-4ac4-814e-d50b26470647.png)

**Comment by davenforce** [comment]
I'm excessively excited about this product. Wishing you well @bitwalker, @bcardarella and the rest of the team!

**Comment by bcardarella** [comment]
@davenforce good news then, @bitwalker has resumed work on Lumen full time as of two weeks ago. We're hoping to get the compiler work pushed up sometime before the Summer.

**Comment by davenforce** [comment]
Fantastic! I'm gassed! Really looking forward to having a LiveView implementation that runs my frontend on the client's machine.

**Comment by howard0su** [comment]
Love to see a todo list so that community can also help.

**Comment by davenforce** [comment]
I'm pulling for you guys! Can't wait to use this library!
